# Usage:
# docker compose --profile all up -d
# docker compose --profile otel-all up -d
# docker compose --profile otel-prometheus up -d
# docker compose --profile otel-grafana up -d
# docker compose --profile otel-jaeger up -d
# docker compose --profile k6-tests up -d
# docker compose --profile sonarqube up -d

include:
  - ./docker/docker-compose.telemetry.multipages.yml
  - ./docker/docker-compose.telemetry.otel.yml
  - ./docker/docker-compose.telemetry.jaeger.yml
  - ./docker/docker-compose.telemetry.prometheus.yml
  - ./docker/docker-compose.telemetry.grafana.yml
  - ./docker/docker-compose.telemetry.k6.yml
  - ./docker/docker-compose.telemetry.sonarqube.yml
