apm-server:
  host: "0.0.0.0:8200"

logging.level: debug

output.elasticsearch:
  hosts: ["http://elastic:9200"]
  username: "elastic"
  password: "elastic"

setup.kibana:
  host: "http://kibana:5601"