# Usage:
# docker compose --profile all up -d

services:
  docker-ui:
    image: docker.io/portainer/portainer-ce
    container_name: portainer
    ports:
      - 9004:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    profiles:
      - all

